apiVersion: apps/v1
kind: Deployment

metadata:
  name: image-2-deployment
  labels:
    app: image-2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-2

  template:
    metadata:
      labels:
        app: image-2

    spec:
      containers:
        - name: image-2-container
          image: us-central1-docker.pkg.dev/faizan-k8s/k8s-assignment/container-two:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: standard-volume
              mountPath: /faizan_PV_dir
      volumes:
        - name: standard-volume
          persistentVolumeClaim:
            claimName: k8s-persistent-volume